name: nexus_app
description: Privacy-first AI productivity suite
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  
  # Navigation
  go_router: ^16.2.4
  
  # Local Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^10.0.0-beta.4
  
  # Utilities
  logger: ^2.0.0
  uuid: ^4.3.0
  intl: ^0.20.2
  
  # Database
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.9.0
  
  # Mock Data
  faker: ^2.1.0
  
  # Audio
  record: ^6.1.1
  just_audio: ^0.10.5
  permission_handler: ^12.0.1
  
  # ML Kit & Speech-to-Text
  google_mlkit_language_id: ^0.13.0
  speech_to_text: ^7.3.0
  tflite_flutter: ^0.11.0
  
  # Sprint 7: Meeting Management UI
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  mockito: ^5.4.0
  golden_toolkit: ^0.15.0
  
  # Drift code generation
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  fonts:
    - family: Nexus
      fonts:
        - asset: fonts/nexus_regular.ttf
        - asset: fonts/nexus_bold.ttf
          weight: 700
