name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/nexus_app/**'
      - '.github/workflows/flutter.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/nexus_app/**'
      - '.github/workflows/flutter.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      working-directory: apps/nexus_app
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
      working-directory: apps/nexus_app
    
    - name: Analyze project source
      run: flutter analyze --fatal-infos
      working-directory: apps/nexus_app
    
    - name: Run tests
      run: flutter test --coverage
      working-directory: apps/nexus_app
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: apps/nexus_app/coverage/lcov.info
        flags: flutter
        name: nexus-flutter-coverage
        fail_ci_if_error: false
    
    - name: Build APK
      run: flutter build apk --release
      working-directory: apps/nexus_app
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: nexus-app-release-apk
        path: apps/nexus_app/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

  build-ios:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      working-directory: apps/nexus_app
    
    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign
      working-directory: apps/nexus_app